import Head from 'next/head'
import styles from './style.module.scss'

const Meta = () => {
  return (
      <Head>
        <title>Next App Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  )
}

export default Meta